### ISSUE TITLE
React-PropTypes-to-prop-types Add unnecessary semicolons

### ISSUE THREAD

**Issue by chentsulin** [reactjs/react-codemod#108]
Should not add semicolons like below:

```diff
- import React, { Component, PropTypes } from 'react'
+ import React, { Component } from 'react';
+ import PropType from 'prop-types';
```

**Comment by notgiorgi** [comment]
If you use eslint, run it with `--fix` flag to remove them.

**Comment by bvaughn** [comment]
Sorry @chentsulin!

I think it's reasonable for the codemod to insert semicolons and for you to remove them via eslint (or similar) if they don't fit your project style. Sorry for the inconvenience!
