### ISSUE TITLE
React-PropTypes to prop types: unnecessary `import 'react'`

### ISSUE THREAD

**Issue by notgiorgi** [reactjs/react-codemod#111]
If I have separate file for proptypes, it still imports react
```diff
-import { PropTypes } from 'react'
+import 'react';
```

**Comment by notgiorgi** [comment]
semicolon issue is already mentioned #108

**Comment by bvaughn** [comment]
I believe this has been fixed in master! Please reply here if I am incorrect. Sorry for the inconvenience.
