### ISSUE TITLE
React-PropTypes did not create new `import` statement

### ISSUE THREAD

**Issue by reergymerej** [reactjs/react-codemod#113]
When a file being transformed requires styles [like this](https://github.com/halt-hammerzeit/webpack-isomorphic-tools#a-simple-example) but uses `import` statements, the transform does not create the `import PropTypes from 'prop-types';`

**Comment by bvaughn** [comment]
This has been fixed in master! Please reply here if I am incorrect. Sorry for the inconvenience.
