### ISSUE TITLE
conversion bug

### ISSUE THREAD

**Issue by ron23** [reactjs/react-codemod#119]
import {Component, PropTypes} from 'react';

converted to:
import { Component } from 'react';

and didn't create 'import PropTypes from 'prop-types';'

using the fixed: https://github.com/solidwareio/react-codemod/commit/7eb11895bcf5148754f159ddbd6364cf1d87e828

Update:
Also:
import {PropTypes} from 'react';
converted to:
import 'react';

**Comment by ron23** [comment]
Not sure that's actually the reason, but I noticed it happens when I have another import:
import ImmutablePropTypes from 'react-immutable-proptypes';

**Comment by bvaughn** [comment]
I believe this has been fixed in master! Please reply here if I am incorrect. Sorry for the inconvenience.
