### ISSUE TITLE
PropTypes transformation completely broken?

### ISSUE THREAD

**Issue by FezVrasta** [reactjs/react-codemod#120]
I'm trying to run the PropTypes transformation on my code base but the only file it (wrongly) updates is a file containing a single propType specification:

```diff
- import { PropTypes } from 'react';
+ import 'react';
export const SEPARATOR = 'separator';

export default {
  type: PropTypes.oneOf([SEPARATOR]),
  value: PropTypes.any,
  label: PropTypes.string,
};
```

All my other files are simply ignored (they are very basic components):

```
Processing 17 files...
Spawning 3 workers...
Sending 6 files to free worker...
Sending 6 files to free worker...
Sending 5 files to free worker...
All done.
Results:
0 errors
0 unmodified
17 skipped
0 ok
```

What happens?

**Comment by andy-j-d** [comment]
I had this same issue. First time I ran it, I got the "name of undefined: error. Re-ran using https://github.com/reactjs/react-codemod/pull/115 and https://github.com/reactjs/react-codemod/pull/116/files, both of which ran without errors but skipped all 100+ files with React.PropTypes imports.

The imports are all either

`import React, { PropTypes } from 'react';`
or
`import React, { Component, PropTypes } from 'react';`

**Comment by FezVrasta** [comment]
Btw I simply used TextMate 2 with:

```
FIND: import React, { PropTypes\,?(.*)} from 'react';
REPLACE: import React, {$1} from 'react';\nimport PropTypes from 'prop-types';
```

```
FIND: import React, { } from 'react';
REPLACE: import React from 'react';
```

Not elegant? Probably. It worked? Absolutely.

**Comment by merlinpatt** [comment]
Why does this cause an issue with some files and not others?

I never used the destructured import and always set propTypes with `React.PropTypes`, so I don't get why I would get this error

**Comment by bvaughn** [comment]
I believe this has been fixed in master! Please reply here if I am incorrect. Sorry for the inconvenience.

**Comment by andy-j-d** [comment]
Getting the same issue with the current master @bvaughn. In this instance 5 of several dozen files that should have been transformed, were. I notice they're all .js extensions, while the majority of our components are .jsx. Is it possible the transform is _only_ looking for .js and skipping .jsx?

**Comment by andy-j-d** [comment]
To run the codemod on js and jsx files, add a `--extensions js jsx`
So nvm @bvaughn, user error.

**Comment by bvaughn** [comment]
By default, `jscodeshift` only processes *.js files. (You can see this by running `jscodeshift --help`). Sounds like you just need to override the default:
```shell
jscodeshift \
  --extensions=js,jsx \
  -t react-codemod/transforms/React-PropTypes-to-prop-types.js \
  <path-to-your-code>
```

**Comment by bvaughn** [comment]
Whoops, looks like you beat me to it. 😄

**Comment by andy-j-d** [comment]
Thanks for the quick response though!

**Comment by LeZuse** [comment]
I also had a problem with this and didn't have much time to investigate the script and fix it. But I liked @FezVrasta solution (thanks for giving me a push!). I just had to improve the first regexp a little bit since our codebase does not have a strict rule on destructured import order:
```
FIND: import React, {((.*?),? ?)?PropTypes\,?(.*)} from 'react';
REPLACE: import React, {$2$3} from 'react';\nimport PropTypes from 'prop-types';
```
