### ISSUE TITLE
class.js complains about deprecated API calls that are not used with React

### ISSUE THREAD

**Issue by Vilkku** [reactjs/react-codemod#123]
Did a dry run and got the following message:

> `Overview` was skipped because of deprecated API calls. Remove calls to getDOMNode, isMounted, replaceProps, replaceState, setProps in your React component and re-run this script.

I do indeed use replaceState, but the context is history.replaceState (https://developer.mozilla.org/en-US/docs/Web/API/History_API), not React, so I believe there should not be a problem, the function names just happen to be the same.

**Comment by threepointone** [comment]
merged your PR, will publish in next patch release, thank you!
