### ISSUE TITLE
`prop-types` codemod fails for explicit, nested destructuring

### ISSUE THREAD

**Issue by mute** [reactjs/react-codemod#134]
Given a `PropTypes` import that looks like this:

```javascript
const {
    PropTypes: {
        shape,
        bool,
        number,
        string
    }
} = React
```

the `prop-types` codemod will insert `import PropTypes from 'prop-types';` but will remove the destructuring assignment completely, leaving `shape`, `bool`, `number`, and `string` undefined.

**Comment by bvaughn** [comment]
Hey @mute! Thanks for filing this!

I don't think we use nested destructuring in FB code much (or at least I haven't seen it).

Would you be interested in submitting a PR to update the codemod to handle this? I'd be happy to review it!

**Comment by mute** [comment]
@bvaughn I put up a PR that does some initial work for it but I don't have enough experience with `recast` or `jscodeshift` to get the builder syntax correct. So, it works but it's not ideal.

If you have the time to update the section where I added the TODO to use the correct builder format to generate a destructuring statement, that would put it in a better place.
