### ISSUE TITLE
Transform file React-PropTypes-to-prop-types.js does not exist 

### ISSUE THREAD

**Issue by jdwinall-tm** [reactjs/react-codemod#137]
I tried to run the script detailed here but the file does not exist in my node_modules directory.

https://github.com/reactjs/react-codemod#react-proptypes-to-prop-types

**steps to reproduce**
1. yarn add jscodeshift react-codemod --D (Installs jscodeshift version 0.3.30 and react-codemod version 4.0.0)
2. node_modules/jscodeshift/bin/jscodeshift.sh -t node_modules/react-codemod/transforms/React-PropTypes-to-prop-types.js components/
3. Error is returned

ERROR Transform file [...]/node_modules/react-codemod/transforms/React-PropTypes-to-prop-types.js does not exist

**Comment by alangpierce** [comment]
@jdwinall-tm The npm package for this project doesn't get released very often (according to https://www.npmjs.com/package/react-codemod it hasn't had a release in 8 months, and React-PropTypes-to-prop-types.js is newer than that). I think the right way to use one of these codemods is to just clone the react-codemod repo from GitHub, separately install jscodeshift, and point jscodeshift at the React-PropTypes-to-prop-types.js file within the cloned repo.

**Comment by jdwinall-tm** [comment]
@alangpierce I agree, but the README.md should be updated capture this.  It states you can install the module using yarn or npm.  I assumed that the readme would be in sync with the code available in the npm package.

**Comment by alangpierce** [comment]
The instructions actually do say to `npm install -g jscodeshift`, then `git clone https://github.com/reactjs/react-codemod.git`, then `npm install` or `yarn` from within the repo (not to run `npm install react-codemod` or `yarn add react-codemod`). But I understand how it could be misread.

IMO it would be best if the npm package was just unpublished to avoid confusion (or there was a deprecation message or something). Or maybe the project could be hooked up to [semantic-release](https://github.com/semantic-release/semantic-release) or some similar system so the npm registry version is automatically kept in sync with the GitHub repo.

(I don't run this project, I've just contributed a few times.)

**Comment by pigflymoon** [comment]
I tried in this way
1.  npm install -g jscodeshift
2. git clone https://github.com/reactjs/react-codemod.git
3. cd react-codemod
4.npm install
5.go to the project which need to transform file, then run this command:

 eg.   jscodeshift -t ../demos/react-codemod/transforms/React-PropTypes-to-prop-types.js ./
which means jscodeshift  find the  React-PropTypes-to-prop-types.js to transform the current whole directory.

Then it works! Hope this will help you.

**Comment by wbeard** [comment]
@alangpierce Would you please cut a release with these new transforms? We have a use case for using `react-codemod` as a locally installed module but will have to copy the source since the transform we want to reference is not available.

**Comment by alangpierce** [comment]
@wbeard I guess you could fork the project and publish it to npm under a new name that you pick. Is there a reason `git clone` as a distribution mechanism doesn't work for you? Arguably it's a little weird to have things installed in node_modules that are neither a library nor a CLI tool, and to need to specify explicit paths to files within node_modules packages.

Here's some prior discussion about the idea of distributing codemods through npm: https://github.com/facebook/jscodeshift/issues/126

**Comment by wbeard** [comment]
Thanks, I'll look over the discussion. I do agree that there could be a better solution for the ecosystem. I'd love to discuss that!

To better explain the use case, we are giving teams a way to easily resolve merge conflicts due to codemods. Our solution, so far, is using an npm script to run `jscodeshift` and a corresponding codemod. When we make large changes, such as moving proptypes, those who need to rebase can just run a script against their local changeset by running `yarn codemod proptypes`. The aim is to reduce friction by reducing the amount of steps to resolve possible conflicts.

There are many ways to do it, and arguably there's not a real need to have an up to date version of the react codemods for any extended length of time. It just seems like a better experience to be able to reach into the library for the source rather than forking or copying. I hope I explained it well!

**Comment by stanlyjohn2** [comment]
When I ran the jscodeshift command, all my files got skipped. What may be the issue?

**Comment by threepointone** [comment]
We just published v5.

**Comment by Punith22bravo** [comment]
i have installed the codemod and jscodeshift by  

 1. npm install -g jscodeshift
 2. git clone https://github.com/reactjs/react-codemod.git
 3.cd react-codemod
 4.npm install
 5.go to the project which need to transform file, then run this command: 
~/React_Launcher$ npx jscodeshift -dpt ~/React_Launcher/react-codemod/transforms/rename-unsafe-lifecycles.js src to update the component lifecycles for my whole project but i am seeing an error as :- 
ERROR Transform file /home/punith/React_Launcher/transform.js does not exist 
could anyone sort me out with the issue
![Screenshot from 2020-07-22 21-25-41](https://user-images.githubusercontent.com/57639155/88199558-a37d9880-cc62-11ea-866c-e27dcd804896.png)

**Comment by threepointone** [comment]
Please file a new issue @Punith22bravo.
