### ISSUE TITLE
RouterContext: React.createClass is deprecated and will be removed in version 16.

### ISSUE THREAD

**Issue by Puneetbh** [reactjs/react-codemod#141]
I have updated my code with codemod and used below command to make changes in node_modules/
command: jscodeshift -t ./transforms/class.js --mixin-module-name=react-addons-pure-render-mixin --flow=true --pure-component=true --remove-runtime-proptypes=false ../ReduxSimpleStarter/node_modules/*

When i compiled my code again its still giving same error, please look into this.

Also facing same issue with PropTypes

**Comment by hmillison** [comment]
If you look at the callstack for this warning. It's originating from `react-router`. You need to upgrade your version to at least 3.0.4 (https://github.com/ReactTraining/react-router/releases/tag/v3.0.4)
