### ISSUE TITLE
errors when 'npm install react-codemod'

### ISSUE THREAD

**Issue by hajush** [reactjs/react-codemod#143]
When I try to install react-codemod via npm, I'm seeing a fatal 'bad object' error:

```
npm install react-codemod@4.0.0
npm ERR! git rev-list -n1 5a5fe8b470e37470744a51678c24ef03b4a8c96b: fatal: bad object 5a5fe8b470e37470744a51678c24ef03b4a8c96b
npm ERR! git rev-list -n1 5a5fe8b470e37470744a51678c24ef03b4a8c96b:
npm ERR! Darwin 16.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "react-codemod@4.0.0"
npm ERR! node v7.7.1
npm ERR! npm  v4.1.2
npm ERR! code 128

npm ERR! Command failed: git rev-list -n1 5a5fe8b470e37470744a51678c24ef03b4a8c96b
npm ERR! fatal: bad object 5a5fe8b470e37470744a51678c24ef03b4a8c96b
npm ERR!
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
```

**Comment by schnerd** [comment]
I'm seeing the same error.

Comes right after `acorn` if that helps at all
```
npm http fetch 200 https://registry.npmjs.org/yargs/-/yargs-3.10.0.tgz
npm http fetch 200 https://registry.npmjs.org/acorn/-/acorn-1.2.2.tgz
npm ERR! git rev-list -n1 5a5fe8b470e37470744a51678c24ef03b4a8c96b: fatal: bad object 5a5fe8b470e37470744a51678c24ef03b4a8c96b
npm ERR! git rev-list -n1 5a5fe8b470e37470744a51678c24ef03b4a8c96b:
npm http fetch GET https://registry.npmjs.org/supports-color/-/supports-color-3.1.2.tgz
npm http fetch 200 https://registry.npmjs.org/supports-color/-/supports-color-3.1.2.tgz
npm http fetch GET https://registry.npmjs.org/camelcase/-/camelcase-1.2.1.tgz
npm http fetch GET https://registry.npmjs.org/esprima-fb/-/esprima-fb-15001.1001.0-dev-harmony-fb.tgz
```

**Comment by anthonyvialleton** [comment]
Same here..

**Comment by benmosher** [comment]
FWIW, docs say to clone from GitHub and then `npm install` deps locally: https://github.com/reactjs/react-codemod#setup--run

This worked for me, after seeing the `git rev-list` failure trying to install from `npm`.

**Comment by benmosher** [comment]
See also: https://github.com/reactjs/react-codemod/issues/137#issuecomment-297790305

**Comment by gaearon** [comment]
It's not meant to be installed from npm.
Please follow the usage instructions.

**Comment by dgoldstein0** [comment]
is there any chance we could get npm support?  My tools work better if this was available via npm; since it isn't I'm going to have to jump through some hoops to get this setup to work.

**Comment by ssotangkur-kahuna** [comment]
@gaearon 
> It's not meant to be installed from npm.
> Please follow the usage instructions.

It would be helpful to say in the instructions that react-codemod isn't meant to be run locally, only globally. Many tools are capable and supportive of being run locally, but are only documented to be run globally. We shouldn't assume that lack of documentation for local running is the same as statement of non-support.
