### ISSUE TITLE
When React is a global variable and not imported by file then files remain unmodified

### ISSUE THREAD

**Issue by DeeLindesay** [reactjs/react-codemod#148]
I'm using
```
\Documents\GitHub> jscodeshift -t react-codemod/transforms/class.js <path to my directory>
```

but it just does not seem to do anying  - I just get
```
Processing 281 files...
Spawning 3 workers...
Sending 50 files to free worker...
Sending 50 files to free worker...
Sending 50 files to free worker...
Sending 50 files to free worker...
Sending 50 files to free worker...
Sending 31 files to free worker...
All done.
Results:
0 errors
281 unmodified
0 skipped
0 ok
```

I'd appreciate any guidance

**Comment by tselishev-semen** [comment]
Try this:
```js
jscodeshift -t react-codemod/transforms/class.js  <path to my directory> --extensions jsx
```
It worked for me

**Comment by DeeLindesay** [comment]
Thanks for responding, but sadly I'm having no luck.  So a file I would expect to be tranformed.
```
const MyComponent = React.createClass({
  render() {

    return pug`
      div
        p  Hello
    `;
  },
});

export default MyComponent;
```
running
```
 jscodeshift -t ../react-codemod/transforms/class.js --remove-runtime-prototypes=false src\components\mycomponent.js
```
gives me
```
Processing 1 files...
Spawning 1 workers...
Sending 1 files to free worker...
All done.
Results:
0 errors
1 unmodified
0 skipped
0 ok
Time elapsed: 1.212seconds
```

**Comment by DeeLindesay** [comment]
However,  if I add `import React from 'react';` to the top of the file then it works.

Trouble is that we declare `React` as a global variable so do not import  it separately in each file.

I will change the title of this issue - if anyone can suggest anything......

**Comment by alangpierce** [comment]
@DeeLindesay try adding `--explicit-require=false` as a jscodeshift arg. That seemed to work for me. From the code ( https://github.com/reactjs/react-codemod/blob/master/transforms/class.js#L1159 ), it needs either that or `ReactUtils.hasReact` (which checks for the import), or else it skips the file.

**Comment by DeeLindesay** [comment]
Thank you.  That definitely gets me onto the right track.
