### ISSUE TITLE
Transforms do not honour tabs over spaces

### ISSUE THREAD

**Issue by cjpete** [reactjs/react-codemod#149]
Particularly with the "manual-bind-to-array.js" where it is amending the constructor, and the defined methods on the class. The replaced text includes spaces for indentation, whereas the whole file utilises tabs (editorconfig also specifies tabs).

**Comment by vcardins** [comment]
+1

**Comment by jsnmoon** [comment]
This is an upstream bug with Recast - see https://github.com/benjamn/recast/pull/404.

**Comment by threepointone** [comment]
sorry about this (and looks like it's not fixed upstream?). The recommendation would be to run prettier (or some other formatter) after running the codemod.
