### ISSUE TITLE
Class.js codemod should fall back to create-react-class when a soon to become arrow function references "arguments" object.

### ISSUE THREAD

**Issue by mareksuscak** [reactjs/react-codemod#163]
Taken from [the MDN docs](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Functions/Arrow_functions#No_binding_of_arguments):

> Arrow functions don't bind an `arguments` object...

Thus _class.js_ transform should check whether or not a soon to become arrow function contains a reference to the `arguments` object. If it does, the codemod must fall back to using _create-react-class_ approach.

Not long after using the codemod, we ran into an issue with this function...

```js

closeAndCall(fn, event) {
  this.close()
  if (fn) {
    fn.apply(this, Array.prototype.slice.call(arguments, 1))
  }
  this.onClearSearchField()
}
```

... which has been transformed into the following piece of code:

```js
closeAndCall = (fn, event) => {
  this.close()
  if (fn) {
    fn.apply(this, Array.prototype.slice.call(arguments, 1))
  }
  this.onClearSearchField()
}
```

Now the _arguments_ var doesn't refer to the list of function arguments as before. Clearly, a solution, in this case, would be:

```js
closeAndCall = (fn, ...args) => {
  this.close()
  if (fn) {
    fn.apply(this, args)
  }
  this.onClearSearchField()
}
```

I might turn this into a PR eventually.

EDIT: 
For convenience, here's a babylon node visitor that finds the occurence:  
https://astexplorer.net/#/gist/2373f28729933bc7aef987a8cec35cd3/de71edf4ffb7e0d3ee390ebbfc3ab7a76739a939

jscodeshift version here: 
https://astexplorer.net/#/gist/2373f28729933bc7aef987a8cec35cd3/ffee55f7af7a3cf1820b907906b24713c3675b59

**Comment by threepointone** [comment]
I’m happy to accept a PR for this.

**Comment by kgrz** [comment]
Dibs.

**Comment by kgrz** [comment]
It looks like the `arguments` bailout check is already included in the heuristics in `class` transform. It's also mentioned in the README, and the commit that added this check was in 2016, so it's not clear to me which condition created this problem. There are tests that verify this behaviour, and [I tried more around the same lines](https://github.com/reactjs/react-codemod/compare/master...kgrz:try-add-failing-test-for-163?expand=1).

That said, the `manual-bind-to-arrow` transform does not have this check and results in arrow function that use `arguments` array. Will try to add a bailout check for that instead.

<img width="1437" alt="Screenshot 2019-11-01 at 08 54 35" src="https://user-images.githubusercontent.com/400299/68000241-55180c00-fc85-11e9-9064-9c8e0deae7f7.png">
