### ISSUE TITLE
feat: convert functional stateless component to class

### ISSUE THREAD

**Issue by AndersDJohnson** [reactjs/react-codemod#168]
This is useful after you realize you need lifecycle hooks.

**Comment by orzarchi** [comment]
I implemented this a codemod:
[orzarchi/react-codemod-pure-component-to-class](https://github.com/orzarchi/react-codemod-pure-component-to-class)
Any feedback will be appreciated

**Comment by mstorus** [comment]
I found another one here 
https://github.com/angryobject/react-pure-to-class/tree/master/packages/react-pure-to-class

**Comment by orzarchi** [comment]
Yep, I stole some code from that one. I didnt like the code it generated so
I made my own version.
