### ISSUE TITLE
Transform all uses of React.createClass to create-react-class

### ISSUE THREAD

**Issue by sseppola** [reactjs/react-codemod#169]
Is there a way to run the class codemod, but force it to always use `create-react-class`?

**Comment by ajb** [comment]
If you're looking for a quick fix, you could modify the source directly. Here's where to do it: https://github.com/reactjs/react-codemod/blob/d8a1d474b6b208cfdbec339b672617270ef78ac5/transforms/class.js#L1213-L1228

**Comment by sseppola** [comment]
@ajb Thank you, that's perfect!
