### ISSUE TITLE
Not all cases are covered by PropTypes codemod

### ISSUE THREAD

**Issue by smolyakoff** [reactjs/react-codemod#171]
Will be nice if `import React, { PropTypes } from 'react';` was also coverted and transformed into two imports.

**Comment by bvaughn** [comment]
This case is already handled (and covered by tests). [This input](https://github.com/reactjs/react-codemod/blob/master/transforms/__testfixtures__/React-PropTypes-to-prop-types/default-and-named-import.input.js) is transformed to [this output](https://github.com/reactjs/react-codemod/blob/master/transforms/__testfixtures__/React-PropTypes-to-prop-types/default-and-named-import.output.js):

### Before
```js
import React, { Component, PropTypes } from 'react';
```

### After
```js
import PropTypes from 'prop-types';
import React, { Component } from 'react';
```
