### ISSUE TITLE
Publishing as a node module more frequently

### ISSUE THREAD

**Issue by wbeard** [reactjs/react-codemod#183]
Hi, we have a use case for wanting to install and use `react-codemod` as a locally installed node module.  

I found in #137 that there may be some barriers preventing you all from publishing a release more often, as well as a suggestion that the package not be installable. I disagree with the latter and would like to understand what the barriers are to making this easier to release on npm and if there's any way I can help.

**Comment by energeek** [comment]
Thanks @wbeard for the shout out. We are facing a similar situation. If publishing is not officially supported, is it possible for us to clone the project and publish a mirror npm package as suggested in #137 ?
