### ISSUE TITLE
Request: follow unix convention for dry-run being -n instead of -d

### ISSUE THREAD

**Issue by jasonkarns** [reactjs/react-codemod#194]
It's a fairly common for many *nix tools to use -n for dry-run. (git, cvs, svn; can't think of any others offhand, but anecdotally seems fairly common)

Would be nice to follow that convention and be less surprising to those who expect that.

**Comment by alangpierce** [comment]
@jasonkarns this repository isn't a CLI tool, it's just a collection of scripts to use with jscodeshift. It sounds like it would be better to file this in the jscodeshift project: https://github.com/facebook/jscodeshift

**Comment by jasonkarns** [comment]
Yep sorry :(

**Comment by threepointone** [comment]
This is now a cli tool :) It has to be an explicit --dry flag.
