### ISSUE TITLE
pure-component name is potentially misleading

### ISSUE THREAD

**Issue by OliverJAsh** [reactjs/react-codemod#196]
The `pure-component` codemod is concerned with stateless function components, not `PureComponent`s. Does this mean the name is potentially misleading?

I have noticed SFCs referred to as "pure (function) components" in a few other places. It would be good if the terminology was used correctly/consistently.

Apologies if I am mislead here!

**Comment by threepointone** [comment]
I agree it's misleading, but we'll keep this around for historical reasons I think.
