### ISSUE TITLE
Use shallowCompare from right place

### ISSUE THREAD

**Issue by zpao** [reactjs/react-codemod#2]
We never shipped it in React.addons. It should be used from `require('react-addons-shallow-compare')`.

(previously filed as https://github.com/facebook/react/issues/4315).

cc @pocketjoso @jardakotesovec

**Comment by cpojer** [comment]
The sad thing about this is that I'll have to add a require/import statement which is hard :)

**Comment by jketcham** [comment]
Can there be something mentioning this in the README perhaps? I just stumbled upon this problem when using react-codemod to update from 13.3 to 14.2, and reading it beforehand would've helped the troubleshooting when upgrading.

**Comment by cpojer** [comment]
I don't think anyone is going to get to this and it's now been so long that few people actually need this particular codemod, so I'm going to go ahead and close this.
