### ISSUE TITLE
SyntaxError: Unexpected token when using class decorators.

### ISSUE THREAD

**Issue by andfelzapata** [reactjs/react-codemod#203]
When using `React-PropTypes-to-prop-types.js` and a class has the @connect decorator, the tool errors: 

`FilePath` Transformation error
SyntaxError: Unexpected token (24:0)

**Comment by nigelwtf** [comment]
Hey @andfelzapata. This is an issue with jscodeshift, specifically the parser it's using. You can opt to use a parser which supports decorators when running the codemod: `--parser babylon`.

**Comment by andfelzapata** [comment]
@nigelwtf Got it, thanks 👍
