### ISSUE TITLE
Any plans to make it work with TypeScript

### ISSUE THREAD

**Issue by milichev** [reactjs/react-codemod#206]
I haven't investigated yet and wonder if anybody else wants something like `--parser typescript`.
What's the feasibility to implement TypeScript processing? I doubt because the TS uses its own AST.

**Comment by mgol-sumo** [comment]
There seem to be `ts & `tsx` parsers:
```
$ jscodeshift --help 
...
      --parser=babel|babylon|flow|ts|tsx  the parser to use for parsing the source files
                                          (default: babel)
...
```
but I've tried them together with the `extensions` option and my files weren't transformed. I tried something like that:
```
jscodeshift --extensions=js,jsx,ts,tsx --parser=tsx -t path
```

**Comment by mgol** [comment]
There seem to be `ts & `tsx` parsers:
```
$ jscodeshift --help 
...
      --parser=babel|babylon|flow|ts|tsx  the parser to use for parsing the source files
                                          (default: babel)
...
```
but I've tried them together with the `extensions` option and my files weren't transformed. I tried something like that:
```
jscodeshift --extensions=js,jsx,ts,tsx --parser=tsx -t path
```

**Comment by threepointone** [comment]
the new cli asks for a language choice when it's run, and choosing typescript adds the required flags automatically. There's a bug in rename-unsafe-lifecycles, fix here https://github.com/reactjs/react-codemod/pull/234(thanks @skovy!) I'll publish an update this weekend.

**Comment by threepointone** [comment]
Published a new version, lemme know if it doesn't work for you folks.

**Comment by LabhanshAgrawal** [comment]
@threepointone I tried to use the TypeScript option but it just skipped all the files, I was able to try it on the js files using the JavaScript option, but the same files got skipped in ts parser.

**Comment by njradford** [comment]
@threepointone I am also seeing the behavior. Works as expected on JSX but TSX gets ignored.

**Comment by threepointone** [comment]
It’s hard to comment without more details. If you could file a fresh issue with more details, what command you ran and what options you picked in the wizard. *Ideally* if you could make a small git repo that reproduces the problem, that would be great.
