### ISSUE TITLE
Getting transformation error 

### ISSUE THREAD

**Issue by pavanshinde47** [reactjs/react-codemod#207]
I am using the below command 
jscodeshift -extensions=js,jsx -t react-codemod/transforms/React-PropTypes-to-prop-types.js \src

and getting the below errors

 ERR src\components\ReactECharts\index.js Transformation error
SyntaxError: Unexpected token (9:18)

 ERR src\routes\app\routes\subscriber\components\PackageAddEquipment.js Transformation error
SyntaxError: Unexpected token, expected "," (195:11)

Does anyone know how to solve this?

**Comment by threepointone** [comment]
This seems like an issue for https://github.com/facebook/jscodeshift/issues

**Comment by vaibhavjagdale** [comment]
I am also getting the same issue and can be solved with --parser.

npx jscodeshift -t ./node_modules/@wdio/codemod/protractor **--parser=ts** ./test/specs/first-test.spec.ts
