### ISSUE TITLE
Move dependencies to devDependencies

### ISSUE THREAD

**Issue by a-axton** [reactjs/react-codemod#209]
Installing this package is causing some errors in my repo. Most of the dependencies should be moved to devDependencies so it doesn't install them unless yarning `yarn/npm install` directly

Currently having issues where this package installs an older version of jest-cli which somehow takes precedence over the jest-cli in jest package.

I saw an open PR for this, was there a reason why it wasn't merged? I wouldn't mind opening one myself if I know it has the possibility of getting merged

**Comment by threepointone** [comment]
fixed in v5
