### ISSUE TITLE
The sort-comp.js transform cannot find a module in my .eslintrc file.

### ISSUE THREAD

**Issue by mrbinky3000** [reactjs/react-codemod#210]
I added a console log to the following code so I could see the specific error being thrown.  
```javascript
function getMethodsOrderFromEslint(filePath) {
  let order;
  const CLIEngine = require('eslint').CLIEngine;
  const cli = new CLIEngine({ useEslintrc: true });
  try {
    const config = cli.getConfigForFile(filePath);
    const {rules} = config;
    const sortCompRules = rules['react/sort-comp'];
    order = sortCompRules && sortCompRules[1].order;
  } catch (e) {
    console.log(e); // <------------------------ I added this 🦄
    // unable to get config for file
  }
  return order;
}
```

and received the following message

```
jscodeshift -t ~/Projects/react-codemod/transforms/sort-comp.js ./CheckoutFormSubmitButton/CheckoutFormSubmitButton.jsx
Processing 1 files...
Spawning 1 workers...
Sending 1 files to free worker...
Error: Cannot find module '@my-private-repo/eslint-config-my-shared-eslint-config'
Referenced from: /Users/me/Projects/demo/app/components/CheckoutFormSubmitButton/.eslintrc
    at ModuleResolver.resolve (/Users/me/Projects/react-codemod/node_modules/eslint/lib/util/module-resolver.js:75:19)
    at resolve (/Users/me/Projects/react-codemod/node_modules/eslint/lib/config/config-file.js:479:33)
    at load (/Users/me/Projects/react-codemod/node_modules/eslint/lib/config/config-file.js:496:24)
    at /Users/me/Projects/react-codemod/node_modules/eslint/lib/config/config-file.js:392:36
    at Array.reduceRight (<anonymous>)
    at applyExtends (/Users/me/Projects/react-codemod/node_modules/eslint/lib/config/config-file.js:363:28)
    at Object.load (/Users/me/Projects/react-codemod/node_modules/eslint/lib/config/config-file.js:530:22)
    at loadConfig (/Users/me/Projects/react-codemod/node_modules/eslint/lib/config.js:64:33)
    at getLocalConfig (/Users/me/Projects/react-codemod/node_modules/eslint/lib/config.js:126:23)
    at Config.getConfig (/Users/me/Projects/react-codemod/node_modules/eslint/lib/config.js:227:22)
All done.
Results:
0 errors
1 unmodified
0 skipped
0 ok
Time elapsed: 1.148seconds
```

sort-comp can't seem to find a eslint module used in my eslintrc file.

When I install the packages as dev dependencies to the react-codemon folder, it gets further along, but eventually still can't find eslint dependencies and crashes.

It seems like react-codemon can only find modules in it's own project folder.

How do you react-codemon to use the node_modules folder in the current project?

**Comment by mrbinky3000** [comment]
I've done more research.  This seems like a bug with the `getConfigForFile()` method of CLIEngine.  It relates to this issue.  https://github.com/eslint/eslint/issues/3458

Basically, `getConfigForFile()` can't follow shared eslint rules.  The tool was written before it was possible to "include" other rules from another file.  The author had never planned for it, and has health issues. 

In my case, '@my-private-repo/eslint-config-my-shared-eslint-config' is causing the break.

My eslint rules adhere to the new React 16.3 lifecyle methods.  We should update the "hard coded" rules that act as a fallback when getConfigForFile fails.  I will make a PR.

**Comment by mrbinky3000** [comment]
I made PR #211 , but I just saw PR #208 which does the same thing, but with less code so it's better.  Go ahead and use #208  :-)

**Comment by threepointone** [comment]
closing this, thank you!
