### ISSUE TITLE
Codemod for switching to new Fragment syntax

### ISSUE THREAD

**Issue by SaladFork** [reactjs/react-codemod#216]
I think it could be nice to have a codemod that automatically replaces `<React.Fragment>`s with the [new short syntax](https://reactjs.org/docs/fragments.html#short-syntax) (`<> ... </>`) where applicable. In fact, a potential codemod was [mentioned in the React v16.2 release blog post that introduced the syntax](https://reactjs.org/blog/2017/11/28/react-v16.2.0-fragment-support.html#other-tools).

If this is welcomed, I wouldn't mind giving this an attempt myself.

Considerations:
 * The new syntax does not support keys or other attributes, so the codemod should not replace any fragments that use them.

**Comment by joshunger** [comment]
@SaladFork this was already added to `eslint-plugin-react`. See https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-fragments.md

**Comment by SaladFork** [comment]
Awesome, thanks!
