### ISSUE TITLE
FR: Convert all class based components to functions with hooks

### ISSUE THREAD

**Issue by brunolemos** [reactjs/react-codemod#217]
### Feature request 

- Convert all class based components to functions
- Convert `state` to `useState` hook
- Use `React.memo` when class extends `PureComponent`
- Move `componentXXXMount` and `componentXXXUpdate` to `useEffect` hook
  - Skip class if it has other lifecycle methods
- Related: Convert `Consumer` render props to `useContext`

#### Bonus points
- TypeScript support
- Flow support

### Possible implementation inspirations
- [Existing codemods](https://github.com/reactjs/react-codemod/tree/master/transforms) from this repo
- [babel-plugin-transform-react-class-to-function](https://github.com/remcohaszing/babel-plugin-transform-react-class-to-function) by @remcohaszing 
- [vscode-react-component-refactor](https://github.com/sanfilippopablo/vscode-react-component-refactor) by @sanfilippopablo

**Comment by brunolemos** [comment]
@remcohaszing

**Comment by brunolemos** [comment]
The wix team released a tool to convert from class to hooks:

https://twitter.com/borislit/status/1093154178556456970
https://github.com/wix/vscode-glean

**Comment by threepointone** [comment]
We don't actually recommend rewriting components with classes into ones with hooks, especially older ones that aren't actively developed. The wix solution looks good for targeted files.  Thanks for the request!

**Comment by karlhorky** [comment]
@threepointone this is an interesting recommendation! Do you have any guidance on the reasoning behind this stance?

The pros and cons I can think of off the top of my head are:

Pros:

- one style (less API surface area, lower learning requirements)
- less code
- potentially, in the future: forwards compatibility (if class components were ever removed from React)
- benefits from new hooks-specific features / tooling

Cons:

- class components still work with current React versions (converting to hooks is for older components almost just "work for work's sake")
