### ISSUE TITLE
findDOMNode script

### ISSUE THREAD

**Issue by lifehackett** [reactjs/react-codemod#22]
Why does the script convert  
`this.refs.injectButton.getDOMNode().focus();`

into
`React.findDOMNode(this.refs.injectButton).focus()`

My understanding of the changes to `refs` is that the original code could be transformed to 
`this.refs.injectButton.focus()`
which if equivalent functionally seems like a better solution.  In the docs it even mentions that using `findDOMNode()` will be unnecessary in most cases.

Was there a specific case you are guarding against to take the more conservative approach?

Thanks

**Comment by cpojer** [comment]
This was unsupported in React previously if I recall correctly and it was the easier upgrade path for us at Facebook.

**Comment by lifehackett** [comment]
Thanks for the quick response.  I'm going to make that change for my own project then since there doesn't seem to be any risk.  Would a PR to update be useful to you?

**Comment by cpojer** [comment]
I don't think there is a way without static typing to say with confidence that the ref you are receiving will be a DOM node. It might be a React component.

**Comment by lifehackett** [comment]
That would be the case if it was one of the native HTML components (e.g. <input>)?

**Comment by cpojer** [comment]
There is no way currently to know in a codemod whether the ref is a React component or a DOM node, yes.

**Comment by lifehackett** [comment]
Ok thanks
