### ISSUE TITLE
Changing from React-dom-factories to React-createElement 

### ISSUE THREAD

**Issue by t3ndai** [reactjs/react-codemod#222]
Are there transforms to change from https://www.npmjs.com/package/react-dom-factories to React CreateElement. Given that this React CodeMod already provides a handy transform for React CreateElement to JSX ?

**Comment by threepointone** [comment]
Not that I know of, but I'm happy to entertain a PR. It's not very useful nowadays tho. CLosing this, but lemme know if you make a PR.
