### ISSUE TITLE
skips .jsx files

### ISSUE THREAD

**Issue by Pixelatex** [reactjs/react-codemod#238]
All transforms seem to ignore all .jsx files, is there some way to tell it to not ignore them?

**Comment by haagvivi** [comment]
I have the same issue, it just check for `.js` file.

**Comment by threepointone** [comment]
I’ll fix this today

**Comment by haagvivi** [comment]
@Pixelatex I finally manage to check `.jsx` files with the `path`. You can pass the `path` in the command, but it only check the first match file.
Example 
```
npx react-codemod rename-unsafe-lifecycles src/**/**.jsx \\ not working !
```
But if you don't specify `path` and in the prompt use `src/**/**.jsx` it will check all the files in `src` folder and subfolder.

**Comment by Pixelatex** [comment]
huh, it might be better to include .jsx in the allowed files though :p or atleast update the docs to allow usage of wildcards in paths and such.

**Comment by threepointone** [comment]
A good workaround is also to pass an option directly to jscodeshift 
```bash
npx react-codemod rename-unsafe-lifecycles --jscodeshift="--extensions=js,jsx"
```

My fix later will make this the default, but this should help for now

**Comment by threepointone** [comment]
I'll also check why `src/**/**.jsx` wasn't working when passed directly

**Comment by threepointone** [comment]
I pushed a fix in https://github.com/reactjs/react-codemod/pull/239. Closing this, but lemme know if you have any problems with it. Thanks!
