### ISSUE TITLE
Unexpected token error while running rename-unsafe-lifecycles transform

### ISSUE THREAD

**Issue by abhisheksoni** [reactjs/react-codemod#240]
Seeing: **Unexpected token ...** error

while running:

> npx react-codemod rename-unsafe-lifecycles

**Comment by threepointone** [comment]
Could you share the file contents on which this error happened? I can't investigate without a repo of some sort.

**Comment by threepointone** [comment]
My best guess is you had an issue with the choice of parser. Closing this, lemme know if you have a repro and I could help.
