### ISSUE TITLE
Update list of options in `--help`  to match available flags

### ISSUE THREAD

**Issue by iamrestrepo** [reactjs/react-codemod#241]
Currently,  when accessing the **--help** command and the **README** to check out the available options/flags to run the **sort-comp** transform, only three **options** are visible to the user:  --force --dry and --print.  Additionally, the  --jscodeshift  flag (for advanced options) suggests that options like  **parse**  and **explicitRequire** can be declared INSIDE this (jscodeshift) instead of just declaring the flags directly when running react-codemod [PATH]  [...options]. 

I suggest we update the README file and the --help script to include all available flags for this transform.

**Comment by threepointone** [comment]
Happy to accept a PR that does so!

**Comment by aulisius** [comment]
I'd like to work on this!

**Comment by threepointone** [comment]
Sure, give it a go! Feel free to ask me questions before you write code.

**Comment by aulisius** [comment]
```
$ react-codemod --help

  Codemods for updating React APIs.

  Usage
    $ npx react-codemod <transform> <path> <...options>

      transform    One of the choices from https://github.com/reactjs/react-codemod
      path         Files or directory to transform. Can be a glob like src/**.test.js

  Options
    --force            Bypass Git safety checks and forcibly run codemods
    --dry              Dry run (no changes are made to files)
    --print            Print transformed files to your terminal
    --explicit-require React should be imported in the file

    --jscodeshift  (Advanced) Pass options directly to jscodeshift

```

@threepointone @iamrestrepo Is this the expected output?

**Comment by threepointone** [comment]
Yeah, looks like we only need to add the explicit-require flag. I'd copy edit that line though, something like "Transform only if React is imported in the file (default: true)".

parse is asked for on startup anyway, so we don't need to add it to this menu.

**Comment by iamrestrepo** [comment]
> ```
> $ react-codemod --help
> 
>   Codemods for updating React APIs.
> 
>   Usage
>     $ npx react-codemod <transform> <path> <...options>
> 
>       transform    One of the choices from https://github.com/reactjs/react-codemod
>       path         Files or directory to transform. Can be a glob like src/**.test.js
> 
>   Options
>     --force            Bypass Git safety checks and forcibly run codemods
>     --dry              Dry run (no changes are made to files)
>     --print            Print transformed files to your terminal
>     --explicit-require React should be imported in the file
> 
>     --jscodeshift  (Advanced) Pass options directly to jscodeshift
> ```
> 
> @threepointone @iamrestrepo Is this the expected output?

Yes! thanks for taking care of it!
