### ISSUE TITLE
Switch to MIT license

### ISSUE THREAD

**Issue by dangreenisrael** [reactjs/react-codemod#243]
Facebook has graciously decided to relicense React under the MIT license and I thought that it may have been an oversight that the React Codemod library didn't have its license updated. If this was on purpose, please feel free to just close this PR.

Thanks so much for all of your amazing contributions to the Open Source community!!!

https://engineering.fb.com/web/relicensing-react-jest-flow-and-immutable-js/

**Comment by threepointone** [comment]
I’m happy to do this, was probably just missed. I’m on PTO, but will do this sooner than later.

**Comment by dangreenisrael** [comment]
Thanks @threepointone
