### ISSUE TITLE
Error when running "manual-bind-to-arrow"

### ISSUE THREAD

**Issue by stekovinbranturry** [reactjs/react-codemod#260]
When there is bind only in constructor, the whole constructor will be removed. Which caused a lot of errors.
![image](https://user-images.githubusercontent.com/33021960/79197617-a51a1200-7e64-11ea-87a6-3f0830813ed9.png)

**Comment by lucasff** [comment]
@stekovinbranturry That's exactly the purpose of this codemod. What's wrong? What's the expected outcome?

**Comment by stekovinbranturry** [comment]
it has been resolved, thanks
