### ISSUE TITLE
Generate `type Props = {...}`

### ISSUE THREAD

**Issue by siderakis** [reactjs/react-codemod#261]
Is there any codemod to generate Props types automatically? Similar to how [this linter plugin](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/prop-types.md) finds undecalred props.

**Comment by lucasff** [comment]
JavaScript by itself has no types. You should look into Flow or TypeScript and their related codemods.

**Comment by threepointone** [comment]
I don't think this would be something this project would include by default. You could consider using a static type system like flow or typescript, or you could of course write your own codemod that does so. Closing this issue, but happy to discuss if there's widespread interest.
