### ISSUE TITLE
$ is not a function

### ISSUE THREAD

**Issue by maraisr** [reactjs/react-codemod#265]
I have tried 3 ways to get this to run:

1. `npx react-codemod` - which produced a `Error: Cannot find module '@babel/runtime-corejs3/helpers/interopRequireDefault'`
1. `yarn add react-codemod` - which produced a `TypeError: $ is not a function @ core-js-pure\modules\es.array.is-array.js:6:1`
1. yarn global add - which produced an another error complaining about module not found (didnt get to catch this error).
1. Running `npx react-codemod` over a clean repo (no local node_modules) - which produced `Error while loading config - Cannot find module '@autoguru/babel-preset/web'`

Also worth mentioning this is windows.

node: v14
yarn: v1.22.4

```sh
yarn list --pattern core-js*
├─ core-js-compat@3.6.5
├─ core-js-pure@3.6.5
└─ core-js@3.6.5

yarn list --pattern @babel/runtime*
├─ @babel/runtime-corejs3@7.10.3
└─ @babel/runtime@7.10.3

# and all other @babel/* are 7.10.3
```

**Comment by threepointone** [comment]
could you try running this command from _outside_ the repo you want changed? so for example if `myproject` is the codebase, don't do `cd myproject && npx react-codemod`, instead run `npx react-codemod myproject` (I hope that's clear, happy to explain further if I'm not)

**Comment by maraisr** [comment]
I tried this! Sadly it did not work. The message is/was the same on both windows and mac. Also with and without the trailing slash.

![image](https://user-images.githubusercontent.com/599459/86848129-d2d3c780-c0f0-11ea-834e-8dfe227df686.png)

**Comment by threepointone** [comment]
Oh hmm that’s odd. I’ll think about it this week, will try to run it on a windows machine too.
