### ISSUE TITLE
Add support for ES6 classes in sort-comp

### ISSUE THREAD

**Issue by lencioni** [reactjs/react-codemod#27]
In a comment in sort-comp, I noticed the following comment:

> NOTE: only works on React.createClass() syntax, not ES6 class.

It would be really lovely if this worked with ES6 classes. :smiley_cat:

**Comment by cpojer** [comment]
we are not taking support requests for this repository. We'll publish React codemods that we build at Facebook and are happy to take pull requests – feel free to dabble into the code and send us one ;)
