### ISSUE TITLE
update-react-imports not working with TS

### ISSUE THREAD

**Issue by mustafawm** [reactjs/react-codemod#273]
Hello,

Not sure if this is related #272 

Following [this (helpful) guide](https://reactjs.org/blog/2020/09/22/introducing-the-new-jsx-transform.html) to try out React 17

`npx react-codemod update-react-imports` is skipping all TS/X files! 

<img width="521" alt="Screen Shot 2020-09-23 at 3 47 06 pm" src="https://user-images.githubusercontent.com/13101565/93971672-0fd85d80-fdb4-11ea-95d6-52480c421540.png">

```jsx
// Sample.tsx
import React, { useState } from 'react';

export default function Sample() {
	const [state, setState] = useState();
	return <p>hello</p>;
}

```

**Comment by mustafawm** [comment]
it's a small codebase, i ended up `find/replace`ing 

`import React from 'react';` with nothing 
and `import React, {` with `import {`

Please close if it's not an issue.

**Comment by gaearon** [comment]
Please try again, this should work now.

**Comment by mustafawm** [comment]
👍 working fine now. Thanks for the quick fix.
