### ISSUE TITLE
Strange output from React-PropTypes-to-prop-types

### ISSUE THREAD

**Issue by kylemh** [reactjs/react-codemod#306]
I'm usually more descriptive about my issues, but not much I can really say! I ran `npx react-codemod React-PropTypes-to-prop-types ./src` and basically my machine bricks and starts spitting out some fun ASCII art 😂 

<img width="1283" alt="Screen Shot 2022-02-18 at 3 29 54 PM" src="https://user-images.githubusercontent.com/9523719/154756913-66b3b6c7-5c48-4b24-9592-a6e1df8cbc58.png">

I'm using the latest version of MacOS on an M1 MacBook Pro. I'm using Node v14 and npm@7.24.2

**Comment by sy19971224** [comment]
Did you solve this problem please?

**Comment by kylemh** [comment]
Yes! I figured out the problem. This dep uses `jscodeshift` which uses `colors.js` and that package was deliberately sabotaged: https://github.com/Marak/colors.js/issues/285.

If you force the resolution of `colors.js` to be a lower version, you should be able to work.

**Comment by kylemh** [comment]
Resolved https://github.com/reactjs/react-codemod/pull/316

**Comment by gaearon** [comment]
Can you verify the fix actually worked?

**Comment by kylemh** [comment]
Verified :)
