### ISSUE TITLE
 react/update-react-imports could not be recognized when running

### ISSUE THREAD

**Issue by RobinVdBroeck** [reactjs/react-codemod#326]
Hello,

When running `npx codemod react/update-react-imports --target src/`, you get the following error:
```
✖ Fetching "react/update-react-imports"...
The specified command or codemod name could not be recognized.
To view available commands, execute "codemod --help".
To see a list of existing codemods, run "codemod search" or "codemod list" with a query representing the codemod you are looking for.
```

The migration also doesn't seem to exist on codemod.com/registery

**Comment by amirabbas-gh** [comment]
Hello Robin!
We published the `react/update-react-imports` on our registry, and now it's available for everyone!
You can use `npx codemod react/update-react-imports` without any problems :)

Please check it out!

**Comment by amirabbas-gh** [comment]
@RobinVdBroeck 

> Hello Robin! We published the `react/update-react-imports` on our registry, and now it's available for everyone! You can use `npx codemod react/update-react-imports` without any problems :)
> 
> Please check it out!

@RobinVdBroeck
