### ISSUE TITLE
Running `codemod` and Getting No Such File or Directory

### ISSUE THREAD

**Issue by jasel-lewis** [reactjs/react-codemod#328]
Updating our project to React v19 and was hoping to use `codemod` as suggested in [the React Upgrade guide](https://react.dev/blog/2024/04/25/react-19-upgrade-guide).

First, attempted to run `npx codemod@latest react/19/migration-recipe` and left all codemods checked, but got:
```txt
Error while running the codemod:
ENOENT: no such file or directory, open 'C:\Users\{redacted}\.codemod\PTYA_Zk6hPg9rLJC2rJnfGMUXLg\index.cjs'
```

The `PTYA_Zk6hPg9rLJC2rJnfGMUXLg` directory exists and has a fair amount of content, but indeed... no `index.cjs` (nor _any_ `index.*` file).

![image](https://github.com/user-attachments/assets/a504814f-1b81-48a3-9bff-346a3122d2bc)

I figured the error may be some artifact of me attempting to run the entire recipe, so I tried `npx codemod react/19/replace-reactdom-render --target ./src` and I got the exact same error (for the exact same directory and `index.cjs` file).

Any help would be greatly appreciated... thank you.

Environment:
- Windows 10 Enterprise v10.0.19045 Build 19045
- NodeJS v20.15.0
- NPM v10.7.0
- `codemod@latest` resolves to v0.11.14

**Comment by jasel-lewis** [comment]
My apology. We run a proxy for the https://registry.npmjs.org repository. Our repo had not updated `codemod`. I am now pulling latest (v0.15.0) and all is well.

Closing this issue report.

**Comment by mohab-sameh** [comment]
Hi @jasel-lewis. Glad to hear it's fixed in the latest version. Happy migrations!
