### ISSUE TITLE
Way to check why files are being skipped

### ISSUE THREAD

**Issue by pruett** [reactjs/react-codemod#41]
Is there a way to see why files are being skipped? It seems like no matter what transform I use, my .js file will be skipped. Thanks.

**Comment by cpojer** [comment]
It is likely that they don't meet any of the basic conditions. For example, we check whether you require React: https://github.com/reactjs/react-codemod/blob/master/transforms/class.js#L499-L501 You can pass `--no-explicit-require` to skip this check.

**Comment by rossPatton** [comment]
I can't get any of the codemod scripts to work on my codebase. Probably because we still use closure. Even with `--no-explicit-require` Having an error message would help me pinpoint what I need to change in order for things to work.

Moving off closure is unfortunately a no-go at this point, and the codebase is big enough that a codemod would save me a lot of time, but at this point it would have been faster to just manually change components like the following to pure components (the mod I was attempting to run)

```javascript
/* @flow */

goog.provide('app.ui.ButtonGroupButton')
goog.require('iod.cx')

goog.scope(function () {

const cx: Function = iod.cx

app.ui.ButtonGroupButton = React.createClass({
  displayName: 'client/ui/button-group-button',

  render () {
    const checked: boolean = this.props.checkedValue === this.props.value
    const btnCx = cx({
      'btn grey-m smallest col no-marg no-rad': true,
      'bg-grey-xxxxl': !checked,
      'active bg-grey-xxxl': checked,
    })

    const btnStyl = {
      borderBottom: !checked ? '3px solid #eaeaea' : '3px solid #36d8cd',
    }

    const handleClick: ?Function = this.props.handleClick ?
      this.props.handleClick.bind(null, this.props.value) :
      null

    return (
      <label
        className={btnCx}
        onClick={handleClick}
        style={btnStyl}>
        <input
          className='seamless'
          name={this.props.group}
          type='radio'
          value={this.props.value}
        />
        {this.props.name}
      </label>
    )
  },

})

})

```

**Comment by cpojer** [comment]
I believe the codemod only looks for var declarations or `module.exports`, so `var Foo = React.createClass` will work but `Foo.bar = React.createClass` will not.

Note that this repo is a self-service repo in that we are happy to accept pull requests but we will not be actively fix community issues. We are simply providing codemods that were useful at Facebook for our codebase or accepting contributions of codemods related to React that other people found useful.

I suggest prototyping a solution in astexplorer.net. See https://github.com/reactjs/react-codemod/blob/master/transforms/utils/ReactUtils.js#L55 and the class transform on how it is being hooked up – if you can fine the correct node in the AST it should be pretty easy to add it to the transform.
