### ISSUE TITLE
PureComponent doesn’t work with React.Component destructured

### ISSUE THREAD

**Issue by camjc** [reactjs/react-codemod#42]
We use
```
import React, { PropTypes, Component } from 'react';

export default class Foo extends Component {
```
and the PureComponent transform skips all of these. Even if this doesn't get fixed its worth noting here in case someone else is wondering why all their files are being skipped.

**Comment by reergymerej** [comment]
`ReactUtils` checks for ES6 class declarations that match the pattern `extends React.Component`.  I'm working on a PR to augment this now.  In the meantime, you can change the class definition and it should work.

**Comment by reergymerej** [comment]
Whoops.  Look like this is dependent on the react-native PR.
