### ISSUE TITLE
sort-comp customization

### ISSUE THREAD

**Issue by reergymerej** [reactjs/react-codemod#44]
It would be nice to pick up the specific sort order defined in .eslintrc if not provided through the CLI options before falling back to the airbnb order.

**Comment by cpojer** [comment]
cc @lencioni

**Comment by lencioni** [comment]
This makes sense to me. I'd be happy to review a PR!

**Comment by reergymerej** [comment]
I'll get on it.

**Comment by cpojer** [comment]
ping? :)

**Comment by reergymerej** [comment]
After a cursory glance, I realized this may be more complex than I thought.  Pulling in eslint config happens in a variety of ways that I don't want to reinvent.  I still think it's a good idea, just not sure how to approach getting the eslint config options smartly.

**Comment by cpojer** [comment]
Is there an API in eslint that gives you a configuration for a given file?

**Comment by reergymerej** [comment]
Not one that I found, surprisingly.  I'd be happy for someone with more Eslint experience to prove me wrong.

**Comment by lencioni** [comment]
You can use ESLint to get the config for any given file. Here's an example:

```js
const cli = new eslint.CLIEngine();
const config = cli.getConfigForFile(PATH_TO_FILE);
```

https://github.com/Galooshi/import-js/blob/dbb69adaff0e4912d9a758e77a9e39cbaf944c03/lib/Importer.js#L102-L103

Docs: http://eslint.org/docs/developer-guide/nodejs-api#getconfigforfile

Although, this might make Jest unhappy: https://github.com/facebook/jest/issues/1048

**Comment by cpojer** [comment]
I'll happily fix the Jest issue. @reergymerej can you make this work?

**Comment by reergymerej** [comment]
@cpojer Yeah, thanks to @lencioni putting me on the right track.  Reading the config seems pretty straight-forward, just trying to figure out how best to get it to play nicely with the *real* lint rules.  I'll try and get a PR soon.

**Comment by cpojer** [comment]
Closing, PR will be merged shortly.
