### ISSUE TITLE
react-to-react-dom does not work with es6 import

### ISSUE THREAD

**Issue by miraage** [reactjs/react-codemod#47]
Files are simply skipped due this code:
```js
        root
            .find(j.CallExpression)
            .filter(p => isRequire(p, coreModuleName))
```

In order to workaround es6 imports there should be something like:
```
        root
            .find(j.ImportDeclaration)
```

I'm dumb in AST, so I can't make a PR.

**Comment by reergymerej** [comment]
There should be at least partial support for this (see #42).  Can you provide an example of the source that is being skipped, please?

**Comment by miraage** [comment]
```
➜  /tmp cat example.js 
import React from 'react';

class Foo extends React.Component {
    randomMethod() {
        React.findDOMNode(this.refs.foo).style.display = 'none';
    }

    render() {
        return <div ref="foo" onClick={::this.randomMethod}>foo</div>;
    }
}
➜  /tmp jscodeshift -t rcm/transforms/react-to-react-dom.js example.js
Processing 1 files... 
Spawning 1 workers...
Sending 1 files to free worker...
All done. 
Results: 
0 errors
1 unmodified
0 skipped
0 ok
Time elapsed: 0.842seconds 
➜  /tmp cat example.js                                                
import React from 'react';

class Foo extends React.Component {
    randomMethod() {
        React.findDOMNode(this.refs.foo).style.display = 'none';
    }

    render() {
        return <div ref="foo" onClick={::this.randomMethod}>foo</div>;
    }
}
```

**Comment by reergymerej** [comment]
Thanks. I'll see if I can get a PR in this afternoon.

**Comment by reergymerej** [comment]
@miraage I just realized this may be intentional.  

> It does not support ES6 modules or other non-CommonJS systems. We recommend performing the findDOMNode conversion first.
[readme][1]

Have you tried running [findDOMNode][2] before react-to-react-dom?

[1]: https://github.com/reactjs/react-codemod#react-to-react-dom 
[2]: https://github.com/reactjs/react-codemod#finddomnode

**Comment by miraage** [comment]
Sure. It worked awesome on code with `this.getDOMNode()`, but not `React.findDOMNode()`.

**Comment by cpojer** [comment]
The react-dom codemod just hasn't been updated. You can send a pull request to add the detection for import statements, just like other codemods do, like the class codemod.

**Comment by reergymerej** [comment]
I'm going to take a stab at this in a minute. There's a util file that I thought all the codemods were using for this sort of thing. I'll try and sort them out.

**Comment by reergymerej** [comment]
Looks like there were no tests for react-to-react-dom, so it's slow going teasing it apart without breaking anything.  I've got a fork that I'm working on I'll submit for a PR, but it won't be quick.

**Comment by miraage** [comment]
@reergymerej thank you.

**Comment by reergymerej** [comment]
You're welcome. I wouldn't close this yet though. ;)
