### ISSUE TITLE
create-element-to-jsx doesn't preserve comments

### ISSUE THREAD

**Issue by alangpierce** [reactjs/react-codemod#59]
It looks like the `create-element-to-jsx` transform silently throws away comments within `React.createElement` calls. Ideally, it should find some way to preserve the comments, or maybe give an error so I can fix those files manually, but if that's too hard or out of scope, I think the behavior should at least be documented.

For example, if you run it on this file:
```js
import React from 'react';

const render = () => {
  return React.createElement('div', {
    className: 'foo',  // This is an important comment.
  });
};
```

It produces this:
```js
import React from 'react';

const render = () => {
  return <div className="foo" />;
};
```

**Comment by cpojer** [comment]
Please note we don't really take support requests for codemods but we happily will accept pull requests that improve them.

cc @TheSavior

**Comment by alangpierce** [comment]
Ok. If it's ok, I'll send a PR to add a warning about the issue to the README. I also may eventually try modifying `create-element-to-jsx` to preserve comments, and I'll send a PR for that if I can get it working.

It might be good if you added a little more context to the README about the purpose and origin of the repo, how suitable the transforms are for general use, and how you approach external contributions/requests. My original impression was that the repo was somewhat "official", and that I could generally trust the transforms to be "safe" in the sense that behavior of the code doesn't change and all comments are preserved.

**Comment by cpojer** [comment]
Sorry, we just don't have the volume to support this repo officially. It is mostly just a collection of react related codemods that we have run either internally at Facebook or that contributors have built. After we are done running a codemod, we usually don't need to run it a second time and we rely on the community to improve the codemods for their use cases.

If you'd like to see this fixed I'd recommend you to send a PR for it including some tests – I'm happy to review and merge it. Comments can usually be transferred simply by doing `newNode.comments = oldNode.comments;` :)

**Comment by alangpierce** [comment]
No problem at all, I understand.

Thanks for the pointer! :-)
