### ISSUE TITLE
React.DOM.div not transformed

### ISSUE THREAD

**Issue by mcmar** [reactjs/react-codemod#74]
I noticed that this will transform `React.createElement`, but not `React.DOM.div`, which is just a convenience wrapper. I have a large codebase that I'm going to need to transform very soon and it's all using `React.DOM.div` (or `span`, `a`, etc). It sounds like it would be easy to make that work the same as `React.createElement`. What do you think?

**Comment by cpojer** [comment]
Yeah, make a codemod using astexplorer and submit a pull request here including tests if you'd like :) We don't really take requests in this repo, we are just sharing codemods that we or others build with more people.

**Comment by alangpierce** [comment]
@mcmar I solved this same problem in the codebase for my company. In my case, we're in the process of converting lots of legacy CoffeeScript without JSX to JavaScript with JSX (mostly using [decaffeinate](http://decaffeinate-project.org/), and one of the later steps (once the code is in JavaScript) is changing our shorthand `rd.div` to `<div>`. I ended up writing a jscodeshift script to convert our shorthand to `React.createElement`, then I use the `create-element-to-jsx` script from this repo.

Here's a gist of the script. It's somewhat specific to my use case, but I bet you could repurpose it to work for you. With some additional work, it may be possible to make it general enough to include in this repo or a similar one. See the comments for more details.
https://gist.github.com/alangpierce/8cad274de23ad9086a6b61dd21f2c22a

**Comment by phiresky** [comment]
@alangpierce thanks, this worked for me with minor modifications.

Another hint, full list of tags from [here](https://github.com/facebook/react/blob/master/src/isomorphic/classic/element/ReactDOMFactories.js) is 

```
'a,abbr,address,area,article,aside,audio,b,base,bdi,bdo,big,blockquote,body,br,button,canvas,caption,cite,code,col,colgroup,data,datalist,dd,del,details,dfn,dialog,div,dl,dt,em,embed,fieldset,figcaption,figure,footer,form,h1,h2,h3,h4,h5,h6,head,header,hgroup,hr,html,i,iframe,img,input,ins,kbd,keygen,label,legend,li,link,main,map,mark,menu,menuitem,meta,meter,nav,noscript,object,ol,optgroup,option,output,p,param,picture,pre,progress,q,rp,rt,ruby,s,samp,script,section,select,small,source,span,strong,style,sub,summary,sup,table,tbody,td,textarea,tfoot,th,thead,time,title,tr,track,u,ul,var,video,wbr,circle,clipPath,defs,ellipse,g,image,line,linearGradient,mask,path,pattern,polygon,polyline,radialGradient,rect,stop,svg,text,tspan'.split(',')
```
