### ISSUE TITLE
Build Warning

### ISSUE THREAD

**Issue by TheSavior** [reactjs/react-codemod#8]
Thanks for updating the test suite. There is currently a build warning:

```
Running 1 test suite...class-test.js: `MyComponent4` was skipped because of invalid field(s) `foo` on the React component. Remove any right-hand-side expressions that are not simple, like: `componentWillUpdate: createWillUpdate()` or `render: foo ? renderA : renderB`.
```

**Comment by cpojer** [comment]
This is actually expected. It is a little unfortunate how we print messages from tests given the parallel nature of jest. This log is coming from the class transform and only means that a class was (correctly) skipped. The test should probably spy on console.log and not actually print this :)
