### ISSUE TITLE
"Cannot read property 'Symbol(Symbol.iterator)' of undefined"

### ISSUE THREAD

**Issue by rubencodes** [reactjs/react-codemod#87]
Wasn't sure if I should report this here or with the `jscodemod` folks. I ran `npm -g list jscodeshift` which installed the latest `jscodeshift`, then tried running:

`jscodeshift -t ~/Downloads/react-codemod-master/transforms/pure-render-mixin.js ./ -d -p`

Which gave me the following error:

```
No files selected, nothing to do. 
(node:1598) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 3): TypeError: Cannot read property 'Symbol(Symbol.iterator)' of undefined
```

Possible separate issue (unsure): I tried running it on a specific file, `./Components/App.jsx`, instead of a `./` path, and I got the following output:

```
Processing 1 files... 
Spawning 1 workers...
Running in dry mode, no files will be written! 
Sending 1 files to free worker...
 ERR ./Components/App.jsx Transformation error
Error: You cannot call "get" on a collection with no paths. Instead, check the "length" property first to verify at least 1 path exists.
    at Error (native)
    at Collection.get (/usr/local/lib/node_modules/jscodeshift/dist/Collection.js:190:13)
    at deletePureRenderMixin (/Users/ruben/Downloads/react-codemod-master/transforms/pure-render-mixin.js:159:54)
    at removePureRenderMixin (/Users/ruben/Downloads/react-codemod-master/transforms/pure-render-mixin.js:180:7)
All done. 
Results: 
1 errors
0 unmodified
0 skipped
0 ok
Time elapsed: 1.130seconds
```

For the record, I'm on node v6.7.0, React 15.3.2, and I just downloaded `react-codemod`.

**Comment by cpojer** [comment]
Sorry, we don't provide help on this repo - it is more self-service as we don't have capacity to provide full open source support :(

**Comment by pbassut** [comment]
@rubencodes When reading the code I noticed it tries to find a PureRenderMixin in the commonJS form:
`var PureRenderMixin = require('react-addons-pure-render-mixin');`

If you have the es6 way, you'll get that error.

so, make sure you apply this transform before applying one that changes your import to es6.
