### ISSUE TITLE
class transform is broken

### ISSUE THREAD

**Issue by kevinbarabash** [reactjs/react-codemod#88]
From the most recent [travis-ci build](https://travis-ci.org/reactjs/react-codemod/builds/173685402):
```
...
     [{kind: method, key: [object Object], value: [object Object], static: false, loc: null, type: MethodDefinition, comments: undefined, computed: false, decorators: null}] does not match field "body": [ClassMethod | ClassProperty] of type ClassBody
      
      at add (node_modules/jscodeshift/node_modules/recast/node_modules/ast-types/lib/types.js:580:31)
      at node_modules/jscodeshift/node_modules/recast/node_modules/ast-types/lib/types.js:593:21
      at Array.forEach (native)
      at Function.Object.defineProperty.value [as classBody] (node_modules/jscodeshift/node_modules/recast/node_modules/ast-types/lib/types.js:592:34)
      at createESClass (transforms/class.js:957:7)
      at NodePath.updateToClass (transforms/class.js:1068:5)
      at node_modules/jscodeshift/dist/Collection.js:76:36
      at Array.forEach (native)
      at Collection.forEach (node_modules/jscodeshift/dist/Collection.js:75:18)
      at apply (transforms/class.js:1137:264)
...
```

I saw the same failures when running `npm install` locally.

Looking at the [build history](https://travis-ci.org/reactjs/react-codemod/builds) it appears that https://github.com/reactjs/react-codemod/commit/84ef7b73b7abc21ee9ca537b59b53bbc0a690ac4 is good but https://github.com/reactjs/react-codemod/commit/509398000bf687b74ef560c8b3de38a6f70a9971 even though the latter didn't introduce any changes into class.js.

I thought maybe it was an issue with the version of jscodeshift I had so I installed 0.3.28 which is what the last passing build installed.  That did not fix the situation so I'm guessing it's some other dependency (or sub-dependency) that's causing the issue.

**Comment by cpojer** [comment]
Oops, something must have gone wrong.

@keyanzhang are you around to help out on this? :)

**Comment by fkling** [comment]
https://github.com/benjamn/ast-types/commit/4c7b343b37ba8ed3efd75fe22de79bc568ad92f8 adds Babel 6 node definitions to ast-types, which seems to override the es6 definitions. cc @hzoo, @benjamn

**Comment by hzoo** [comment]
Ah ok, sorry about that @kevinbarabash will look into it

**Comment by hzoo** [comment]
Made a PR https://github.com/benjamn/ast-types/issues/194

**Comment by kevinbarabash** [comment]
@hzoo thanks.

**Comment by kevinbarabash** [comment]
I reinstalled my version jscodeshift and things seem to be working.  Some of the react-codemod tests are still failing b/c of what looks like dangling comma differences in the fixtures.

**Comment by keyanzhang** [comment]
Hmm, a rest parameter should never have a trailing comma. I'll fix it.

**Comment by keyanzhang** [comment]
Also submitted benjamn/recast#341 to control the printing of spaces inside array and object patterns. Let's keep this issue open for visibility until tests pass. Thanks @kevinbarabash!
