### ISSUE TITLE
Don't skip files conversion because of mixins?

### ISSUE THREAD

**Issue by mladenp** [reactjs/react-codemod#89]
I want to leave mixins and use them with a 3rd party lib.
When i try to convert components that have mixins in them they get skipped, can i somehow ignore that and still convert components to classes?

**Comment by rosswarren** [comment]
@mladenp I don't think there is a reliable way to get mixins working in ES6 React classes. What are you expecting the output to be after the conversion has completed?

I think the expectation is that you refactor your `React.createClass` component to no longer depend on a mixin before running the conversion to some other technique like using a higher-order component.

**Comment by mladenp** [comment]
It seems you are right, i didn't think of that. I can't just leave mixins 'as is' even with 3rd party lib for mixins in ES6 because of different syntax.
Ii'll need to rewrite those components manually any way.
